function k(b,a,c,d){b.s.Db(b.jb,a,c,d,void 0)}function l(b,a,c,d){b.s.ca?k(b,a,c,d):b.s.ue()._OnMessageFromDOM({type:"event",component:b.jb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.s.C(b.jb,a,c)}function n(b,a){for(const [c,d]of a)aa(b,c,d)}function t(b){b.Pb||(b.s.fd(b.Od),b.Pb=!0)}window.bb=class{constructor(b,a){this.s=b;this.jb=a;this.Pb=!1;this.Od=()=>this.La()}Yc(){}La(){}};
window.cf=class{constructor(){this.Vc=-1}j(){-1!==this.Vc&&(self.clearTimeout(this.Vc),this.Vc=-1)}};"use strict";function ba(b,a){aa(b,"get-element",c=>{const d=u(b,c.elementId);return a(d,c)})}function u(b,a){b=b.Nb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.rd}
window.bf=class extends self.bb{constructor(b,a){super(b,a);this.Nb=new Map;this.Dc=!0;n(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=u(this,c);this.Dc&&d.parentElement.removeChild(d);this.Nb.delete(c)}],["set-visible",c=>{if(this.Dc){var d=this.Nb.get(c.elementId),e=d.rd;d.xd?e.style.display=c.isVisible?"":"none":d.Je=!!c.isVisible}}],["update-position",c=>{if(this.Dc){var d=this.Nb.get(c.elementId),e=d.rd;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.xd||(d.xd=!0,d.Je&&(e.style.display=""))}}],["update-state",c=>{u(this,c.elementId);throw Error("required override");}],["focus",c=>this.yc(c)],["set-css-style",c=>{const d=u(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{u(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{u(this,c.elementId).removeAttribute(c.name)}]]);
ba(this,c=>c)}yc(b){var a=u(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Se?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.We+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let y=new Audio;
const ja={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}
function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let C=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let oa=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.Aa=class b{constructor(a){this.ca=a.Ye;this.va=null;this.ba="";this.Ya=a.Ve;this.zb={};this.Ra=this.ta=null;this.Mb=[];this.H=this.wa=null;this.Lc=!1;this.ud=0;this.ob=null;this.Xa=-1;this.Ne=()=>this.Be();this.Wa=[];this.v=a.Pd;this.Qb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.ca=!1);this.ca&&da&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(v){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Tb=this.qa=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.xe(c));this.C("runtime","create-job-worker",()=>this.ye());"cordova"===this.v?document.addEventListener("deviceready",
()=>this.jd(a)):this.jd(a)}j(){this.rc();this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ra&&(this.Ra.j(),this.Ra=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}je(){return ca&&"cordova"===this.v}nc(){const a=navigator.userAgent;return ca&&qa.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}he(){return v}cd(){return v&&qa.has(this.v)}async jd(a){"macos-wkwebview"===this.v&&this.Bc({type:"ready"});if("playable-ad"===
this.v){this.qa=self.c3_base64files;this.Tb={};await this.qe();for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Tb.hasOwnProperty(c)?a.$a[d]={Se:!0,We:this.Tb[c]}:this.qa.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.qa[c]))}a.fc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.fd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ue?this.ba=a.Ue:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),
-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.$e&&(this.zb=a.$e);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ae(d));this.ob=new self.ke(this);await sa(this.ob);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.we(a,c.port2):await this.ve(a,c.port2)}tc(a){a=this.zb.hasOwnProperty(a)?this.zb[a]:a.endsWith("/workermain.js")&&this.zb.hasOwnProperty("workermain.js")?this.zb["workermain.js"]:"playable-ad"===this.v&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ic(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Qb)return a=await this.Bb(d.Re?a:this.Ya+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}hd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ia(),g=window.devicePixelRatio,h=b.fb(),m=a.hf,q=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.ff||
"";a=a.Pd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.ob;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:p,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.gf,jobScheduler:{inputPort:B.Kc,outputPort:B.Rc,maxNumWorkers:B.Ke},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Ya+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Ya+"opus.wasm.wasm",isFileProtocol:this.Qb,isiOSCordova:this.je(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async we(a,c){const d=this.tc(a.Ze);"preview"===this.v?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=p=>{this.ta.removeEventListener("message",q);p.data&&"ok"===p.data.type?h():m()};this.ta.addEventListener("message",q);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.ic(d,this.ba,{type:"module",name:"Runtime",Re:!0});this.H=document.createElement("canvas");this.H.style.display="none";const e=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.fc||[],g=a.$a;f=await Promise.all(f.map(h=>this.Ma(h)));g=await Promise.all(g.map(h=>this.Ma(h)));if("cordova"===this.v)for(let h=0,m=a.ec.length;h<m;++h){const q=
a.ec[h],p=q[0];if(p===a.Wc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))q[1]=await this.Ma(p)}this.ta.postMessage(Object.assign(this.hd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ec,mainProjectScript:a.Wc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ta(this.ob)]);this.Mb=E.map(h=>new h(this));this.gd();ua(this.wa);self.c3_callFunction=(h,m)=>{var q=this.wa;return q.s.ed(q.jb,"js-invoke-function",
{name:h,params:m},void 0,void 0)};"preview"===this.v&&(self.goToLastErrorScript=()=>this.Db("runtime","go-to-last-error-script"))}async ve(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Mb=E.map(g=>new g(this));this.gd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.fc)&&d.unshift(...a.fc);d=await Promise.all(d.map(g=>
this.Ma(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;const e=a.Wc,f=a.ec;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ma(h),await w(h),"preview"!==this.v||d[g]||this.ld(g,"main script did not run to completion")}catch(m){this.ld(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ma(h),await w(h);"preview"===this.v&&"object"!==typeof self.af.df?(this.Hb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.hd(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:pa}),ua(this.wa),this.kd(),this.Ra=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ra,a))}ld(a,c){this.Hb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}kd(){this.Hb()}Hb(){const a=
window.Pe;a&&(a.parentElement.removeChild(a),window.Pe=null)}async ye(){const a=await va(this.ob);return{outputPort:a,transferables:[a]}}ue(){if(this.ca)throw Error("not available in worker mode");return this.Ra}Db(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ed(a,c,d,e,f){const g=oa++,h=new Promise((m,q)=>{G.set(g,{resolve:m,reject:q})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.ze(a);if("result"===c)this.Ce(a);else if("runtime-ready"===c)this.De();else if("alert-error"===c)this.Hb(),alert(a.message);else if("creating-runtime"===c)this.kd();else throw Error(`unknown message '${c}'`);}ze(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Gb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Gb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Gb(f,!1,""+h)}):this.Gb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Gb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ce(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}C(a,
c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ab(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}gd(){for(const a of this.Mb)if("runtime"===a.jb){this.wa=a;return}throw Error("cannot find runtime DOM handler");}Ae(a){this.Db("debugger","message",a)}De(){for(const a of this.Mb)a.Yc()}static fb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
ra)}static Ib(a){ra=!!a}fd(a){this.Wa.push(a);this.Ac()}Fe(a){a=this.Wa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Wa.splice(a,1);this.Wa.length||this.rc()}Ac(){-1===this.Xa&&this.Wa.length&&(this.Xa=requestAnimationFrame(this.Ne))}rc(){-1!==this.Xa&&(cancelAnimationFrame(this.Xa),this.Xa=-1)}Be(){this.Xa=-1;for(const a of this.Wa)a();this.Ac()}Ca(a){this.wa.Ca(a)}Ka(a){this.wa.Ka(a)}zc(){this.wa.zc()}Fb(a){this.wa.Fb(a)}ie(){return!!ja["audio/webm; codecs=opus"]}async Ge(a){a=await this.ed("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}me(a){this.Lc=!0;this.ud=a}ge(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}dd(a){return!this.ge(a)}async Ma(a){return"cordova"===this.v&&(a.startsWith("file:")||this.Qb&&this.dd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Bb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async xe(a){const c=a.filename;switch(a.as){case "text":return await this.fe(c);
case "buffer":return await this.Bb(c);default:throw Error("unsupported type");}}ad(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async fe(a){a=await this.ad(a);return await ma(a)}sc(){if(z.length&&!(8<=C)){C++;var a=z.shift();this.re(a.filename,a.Xe,a.Qe)}}Bb(a){return new Promise((c,d)=>{z.push({filename:a,Xe:e=>{C--;this.sc();c(e)},Qe:e=>{C--;this.sc();d(e)}});this.sc()})}async re(a,c,d){try{const e=
await this.ad(a),f=await na(e);c(f)}catch(e){d(e)}}Bc(a){if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async qe(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.pe(c,d));await Promise.all(a)}async pe(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Tb[a]=c.str;else{let d=
await this.te(c);d||(d=this.se(c));this.qa[a]=d}}async te(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}se(a){a=this.Ee(a);return this.oe(a.data,a.Te)}Ee(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Te:a,data:d}}oe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.Aa;
function wa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const xa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ya={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ba(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Ba(b)}finally{URL.revokeObjectURL(b)}}
function Ca(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Da(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Ca(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function ua(b){b.td=!0;b.Oc=b.s.oa();b.pb=b.s.ia()}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.sd=!0},1E3);"cordova"===b.s.v?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ia)}}
function Pa(b){b.nd||(b.nd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Qa(b){b.md||(b.md=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Ra(b){await za(b.url)}
function Sa(b,a){b.vd=a.message;-1===b.Gc&&(b.Gc=setTimeout(()=>{b.Gc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.vd)},250))}function M(b){if(!b.Z){var a=H.fb();a&&"any"!==b.Tc&&Ta(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ia()})}}function Ua(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.fb(),innerWidth:b.oa(),innerHeight:b.ia()})}
function Oa(b,a){a?b.s.rc():b.s.Ac();k(b,"visibilitychange",{hidden:a})}function Va(b,a,c){"Backspace"===c.key&&L(c);if(!b.Z){var d=xa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Wa(b,a,c,d){b.Z||wa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Xa(b){window!==window.top&&window.focus();Ya(b.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Z){var d=0;"mouse"===c.pointerType&&(d=b.ub);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Wa(b,d,c,ya),b.ub=c.buttons)}}
function Za(b,a,c){if(!b.Z&&!wa(c)){var d=b.ub;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.ub=c.buttons;Wa(b,c.type,c,ya)}}
function O(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function $a(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function cb(b,a,c,d){const e=b.oa(),f=b.ia();b.Za=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.fb()}):10>d&&db(b,e,f,d+1)}
function db(b,a,c,d){-1!==b.Za&&clearTimeout(b.Za);b.Za=setTimeout(()=>cb(b,a,c,d),48)}
function Ta(b){b=b.Tc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Ab(class extends self.bb{constructor(b){super(b,"runtime");this.Bd=!0;this.td=!1;this.Za=-1;this.Tc="any";this.md=this.nd=!1;this.bc=document.createElement("div");this.bc.className="c3-screen-reader-text";this.bc.setAttribute("aria-live","polite");document.body.appendChild(this.bc);this.Fa=null;this.Z=!1;this.vd="";this.Gc=-1;this.sd=!1;this.Oc=b.oa();this.pb=b.ia();this.da=this.yb=0;b.C("canvas","update-size",d=>{var e=this.s;e.Lc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Bd&&(e.style.display="",this.Bd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ja(d));b.C("runtime","raster-svg-image",d=>Ka(d));b.C("runtime","get-svg-image-size",
d=>La(d));b.C("runtime","set-target-orientation",d=>{this.Tc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ma(d));b.C("runtime","go-to-script",d=>Ma(d));b.C("runtime","before-start-ticking",()=>Na(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var e=this.Fa;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Fa&&(this.Fa.style.display="none")});b.C("runtime","enable-device-orientation",()=>Pa(this));b.C("runtime","enable-device-motion",()=>Qa(this));b.C("runtime","add-stylesheet",d=>Ra(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.wc(d));b.C("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.bc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.H.style.display="";this.s.me(d.duration)});b.C("runtime","export-to-video-progress",d=>Sa(this,d));b.C("runtime","exported-to-video",d=>{window.Oe({type:"exported-video",
blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Oe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ea(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",L);window.addEventListener("touchstart",
L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.ub=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.td){var d=this.oa();var e=this.ia();if(this.s.cd()){if(this.sd){if(this.Oc===d&&
e<this.pb){this.yb=this.pb-e;$a(this,this.pb,this.yb);d=void 0;break a}0<this.yb&&(this.yb=0,$a(this,e,this.yb))}this.Oc=d;this.pb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.fb()});this.s.nc()&&(-1!==this.Za&&clearTimeout(this.Za),cb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>
M(this));window.addEventListener("fullscreenerror",d=>Ua(this,d));window.addEventListener("webkitfullscreenerror",d=>Ua(this,d));window.addEventListener("mozfullscreenerror",d=>Ua(this,d));if(b.nc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ea(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.Ib(!0),M(this)):"exited-fullscreen"===d?(H.Ib(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Sa=new Set;this.Vb=new WeakSet;this.ua=!1}Yc(){window.addEventListener("focus",()=>{k(this,"window-focus",null,J)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},J);this.ub=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||Ea(a))&&k(this,"keyboard-blur",null,J)});window.addEventListener("keydown",a=>Va(this,"keydown",a));window.addEventListener("keyup",a=>Va(this,"keyup",a));window.addEventListener("dblclick",a=>Wa(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,
deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Xa(a);N(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Xa(a);Za(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Za(this,"pointermove",a)),window.addEventListener("mouseup",a=>Za(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Xa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=
()=>this.zc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.he()&&!this.s.cd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{$a(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.s.oa()}ia(){return this.s.ia()}zc(){var b=
[...this.Sa];this.Sa.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Vb.has(a)||this.Sa.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.Vb.delete(b);let a;try{a=b.play()}catch(c){this.Sa.add(b);return}a&&a.catch(()=>{this.Vb.has(b)||this.Sa.add(b)})}Ka(b){this.Sa.delete(b);this.Vb.add(b)}Fb(b){this.ua=!!b}wc(b){alert(b.message)}});"use strict";
async function sa(b){if(b.He)throw Error("already initialised");b.He=!0;var a=b.xa.tc(("playable-ad"===b.xa.v?b.xa.Ya:"")+"dispatchworker.js");b.Fc=await b.xa.ic(a,b.ib,{name:"DispatchWorker"});a=new MessageChannel;b.Kc=a.port1;b.Fc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Rc=await va(b)}function ta(b){return[b.Kc,b.Rc]}
async function va(b){const a=b.Cd.length;var c=b.xa.tc(("playable-ad"===b.xa.v?b.xa.Ya:"")+"jobworker.js");c=await b.xa.ic(c,b.ib,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Fc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Cd.push(c);return e.port1}
self.ke=class{constructor(b){this.xa=b;this.ib=b.ba;this.ib="preview"===b.v?this.ib+"workers/":this.ib+b.Ya;this.Ke=Math.min(navigator.hardwareConcurrency||2,16);this.Fc=null;this.Cd=[];this.Rc=this.Kc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Aa({Ye:!1,Ze:"workermain.js",$a:["scripts/c3runtime.js"],ec:[],Wc:"",Ve:"scripts/",fc:[],Pd:"html5"}));"use strict";
self.Aa.Ab(class extends self.bb{constructor(b){super(b,"mouse");n(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.s.H.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function eb(){}function fb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function gb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.Aa.Ab(class extends self.bb{constructor(b){super(b,"browser");this.v="";n(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
fb(this)],["alert",a=>this.wc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.yc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>gb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.ef||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.v||"macos-wkwebview"===this.v)self.Aa.Ib(!0),this.s.Bc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(eb)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.v||"macos-wkwebview"===
this.v)self.Aa.Ib(!1),this.s.Bc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(eb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=
Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),
c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}wc(b){alert(b.message)}yc(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
"use strict";const hb=180/Math.PI;
async function ib(b,a){if(a.isiOSCordova||a.isSafari)b.Yb=!0;b.Uc=a.timeScaleMode;b.Hd=["equalpower","HRTF","soundfield"][a.panningModel];b.qd=["linear","inverse","exponential"][a.distanceModel];b.Id=a.refDistance;b.Gd=a.maxDistance;b.Kd=a.rolloffFactor;if(b.s.Lc)b.Yb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.ud)});else{var c={latencyHint:a.latencyHint};b.Nd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");jb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&jb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Oa=b.g.createGain();b.Oa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function kb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,p=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Dd=g;lb(b,g);try{b.$=await mb(b,c,d,e,g,f);if(p){Q(b.$,!0);var r=b.$,B=p.innerAngle,ka=p.outerAngle,la=p.outerGain;if(r.nb){nb(r,p.x,p.y,p.z,p.angle);var D=self.ab.ne;r.ra[0]!==D(B)&&(r.ra[0]=
D(B),r.F.coneInnerAngle=D(B));r.ra[1]!==D(ka)&&(r.ra[1]=D(ka),r.F.coneOuterAngle=D(ka));r.ra[2]!==la&&(r.ra[2]=la,r.F.coneOuterGain=la)}p.hasOwnProperty("uid")&&(b.$.pa=p.uid)}else"number"===typeof A&&0!==A?(R(b.$,!0),ob(b.$,A)):(Q(b.$,!1),R(b.$,!1));b.$.Play(h,m,q,x)}catch(zb){console.error("[Construct] Audio: error starting playback: ",zb);return}finally{c=b.wb.get(g);if(!c)throw Error("expected pending tag");c.Xc--;0===c.Xc&&(c.resolve(),b.wb.delete(g))}t(b)}
async function pb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await qb(b,c);for(const p of S(b,c)){c=p;var f=d,g=e,h=a;if(!c.Qa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.u.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ia=f;c.Pa=g;c.Md=h}}T(b)}async function rb(b,a){const c=a.tag;a=a.rate;await qb(b,c);for(const d of S(b,c))b=d,b.ma!==a&&(b.ma=a,b.Da())}
async function sb(b,a){const c=a.tag;a=a.pos;await qb(b,c);for(const d of S(b,c))d.oc(a)}async function tb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await mb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function ub(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function vb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Vd(b,...e);else if("delay"===c)e=new self.Td(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Sd(b,c.ja,...e);var f=a.bufferType;c.od=a.bufferOriginalUrl;c.pd=f}else if("flanger"===c)e=new self.Wd(b,...e);else if("phaser"===c)e=new self.Yd(b,...e);else if("gain"===c)e=
new self.Xd(b,...e);else if("stereopan"===c)e=new self.$d(b,...e);else if("tremolo"===c)e=new self.ae(b,...e);else if("ringmod"===c)e=new self.Zd(b,...e);else if("distortion"===c)e=new self.Ud(b,...e);else if("compressor"===c)e=new self.Rd(b,...e);else if("analyser"===c)e=new self.Qd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.la.get(d);e||(e=[],b.la.set(d,e));a.Ad=e.length;a.ga=d;e.push(a);wb(b,d);xb(b)}
async function yb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.J)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.J=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.cc=a.timeScale;b.Hc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.ua=a.isSilent;b.s.Fb(b.ua);b.Ub=a.masterVolume;b.Oa.gain.value=
b.Ub;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>vb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ab(b,f,c)));T(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.zd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.Db("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.zd=!0);await c}catch(c){Cb(c)}}
function jb(b){b.Ob||(b.Jc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Ob=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ka)if(g.eb()===c)return await Db(g),g;if(f)return null;if(e&&(b.Yb||b.yd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.za()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Nd;e&&f&&(b.yd=!0);c=!e||b.Yb||f?new self.de(b,a,c,d,e,f):new self.be(b,a,c,d,e);b.ka.push(c);await Db(c);b.Fd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Fd.add(a));return c}
function Eb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.na()}function wb(b,a){let c=b.na();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ga&&b.Pc===a&&(b.Ga.disconnect(),b.Ga.connect(c))}
function*S(b,a){if(a)for(const c of b.J)b=c.ga,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Fb(b,a,c){return c?b.s.Ge(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Gb(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.O===a?f.j():++c}b.J.length=c}
async function mb(b,a,c,d,e,f){for(const g of b.J)if(g.eb()===c&&(g.hc()||f))return g.ga=e,g;a=await P(b,a,c,d,f);e="html5"===a.Cc?new self.ce(a.u,a,e):new self.ee(a.u,a,e);b.J.push(e);return e}function lb(b,a){let c=b.wb.get(a);if(!c){let d=null;c={Xc:0,promise:new Promise(e=>d=e),resolve:d};b.wb.set(a,c)}c.Xc++}function qb(b,a){a||(a=b.Dd);return(b=b.wb.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Na.size)t(b);else for(const a of b.J)if(!a.I&&!a.U()){t(b);break}}
function Hb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function xb(b){b.Mc||(b.Mc=!0,Promise.resolve().then(()=>Ib(b)))}function Ib(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.cb());k(b,"fxstate",{fxstate:a});b.Mc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await mb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],f=d.orient,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],e.setPosition(...b.Ua),e.setOrientation(...b.Ta),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),ob(b,d));c.Play(m,q,p,0);a.isPlaying||c.gb();c.vc(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ab=class extends self.bb{constructor(b){super(b,"audio");this.Oa=this.g=null;this.Ob=this.Jc=!1;this.ya=()=>{if(!this.Jc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ob&&(this.Jc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Ob=!1)}};this.ka=[];this.J=[];this.$=null;this.Dd="";this.Fd=new Set;this.Ed=-1;this.wb=new Map;this.Ub=1;this.ua=!1;this.Uc=0;this.cc=1;this.Hc=0;this.Hd="HRTF";this.qd="inverse";this.Id=600;this.Gd=1E4;this.Kd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.yd=this.Yb=!1;this.Nd=this.s.ie();this.la=new Map;this.Na=new Set;this.zd=this.Mc=!1;this.Pc="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ga&&this.Ga.disconnect();this.Pc=c.toLowerCase();this.Ga=this.g.createMediaStreamSource(a);
this.Ga.connect(Eb(this,this.Pc))};this.Lb=null;self.C3Audio_GetOutputStream=()=>{this.Lb||(this.Lb=this.g.createMediaStreamDestination(),this.Oa.connect(this.Lb));return this.Lb.stream};self.C3Audio_DOMInterface=this;n(this,[["create-audio-context",a=>ib(this,a)],["play",a=>kb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.J)a.Ba()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.gb():d.Eb();T(this)}],["set-volume",a=>
{const c=a.tag;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>pb(this,a)],["set-master-volume",a=>{this.Ub=a.vol;this.Oa.gain.value=this.Ub}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Jb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.s.Fb(this.ua);for(const c of this.J)c.Jb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.pc(a)}],["set-playback-rate",a=>rb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,
c))R(d,!0),ob(d,a)}],["seek",a=>sb(this,a)],["preload",a=>tb(this,a)],["unload",a=>ub(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.J)c.qc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>vb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.la.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),xb(this))}],["remove-effects",a=>
{a=a.tag.toLowerCase();const c=this.la.get(a);if(c&&c.length){for(const d of c)d.j();this.la.delete(a);wb(this,a)}}],["tick",a=>{this.cc=a.timeScale;this.Hc=a.gameTime;this.Ed=a.tickCount;if(0!==this.Uc)for(var c of this.J)c.Da();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==
c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.J)e.pa===a&&nb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>yb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Oa}Cb(){return this.ua}Ca(b){this.s.Ca(b)}Ka(b){this.s.Ka(b)}La(){for(var b of this.Na)b.La();b=this.g.currentTime;for(var a of this.J)a.La(b);
a=this.J.filter(c=>!c.I&&!c.U()).map(c=>c.cb());k(this,"state",{tickCount:this.Ed,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Na].map(c=>({tag:c.ga,index:c.Ad,peak:c.Va,rms:c.Jd,binCount:c.l.frequencyBinCount,freqBins:c.wd}))});0===a.length&&0===this.Na.size&&this.Pb&&(this.s.Fe(this.Od),this.Pb=!1)}static ne(b){return b*hb}static bd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static le(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.Aa.Ab(self.ab);
"use strict";function Db(b){b.Sb||(b.Sb=b.uc());return b.Sb}self.Zc=class{constructor(b,a,c,d,e){this.u=b;this.Me=a;this.Ha=c;this.R=d;this.Ie=e;this.Cc="";this.Sb=null}j(){this.Sb=this.u=null}uc(){}V(){return this.u.V()}kc(){return this.Me}eb(){return this.Ha}jc(){return this.R}za(){return this.Ie}ha(){}};"use strict";
self.be=class extends self.Zc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Cc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.qb=this.rb=null;this.M.addEventListener("canplaythrough",()=>!0);this.vb=this.V().createGain();this.tb=null;this.M.addEventListener("canplay",()=>{this.rb&&(this.rb(),this.qb=this.rb=null);!this.tb&&this.M&&(this.tb=this.V().createMediaElementSource(this.M),this.tb.connect(this.vb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ha}' error: `,f);this.qb&&(this.qb(f),this.qb=this.rb=null)})}j(){Gb(this.u,this);this.vb.disconnect();this.vb=null;this.tb.disconnect();this.tb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}uc(){return new Promise((b,a)=>{this.rb=b;this.qb=a;this.M.src=this.Ha})}T(){return this.M}ha(){return this.M.duration}};"use strict";
async function Kb(b){if(b.Ea)return b.Ea;var a=b.u.s;if("cordova"===a.v&&a.dd(b.Ha)&&a.Qb)b.Ea=await a.Bb(b.Ha);else{a=await fetch(b.Ha);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ea=await a.arrayBuffer()}}async function Lb(b){if(b.ja)return b.ja;b.ja=await Fb(b.u,b.Ea,b.Le);b.Ea=null}
self.de=class extends self.Zc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Cc="webaudio";this.ja=this.Ea=null;this.Le=!!f}j(){Gb(this.u,this);this.ja=this.Ea=null;super.j()}async uc(){try{await Kb(this),await Lb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ha}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Mb=0;
function Q(b,a){a=!!a;b.nb!==a&&(b.nb=a,b.nb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Hd,b.F.distanceModel=b.u.qd,b.F.refDistance=b.u.Id,b.F.maxDistance=b.u.Gd,b.F.rolloffFactor=b.u.Kd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Rb!==a&&(b.Rb=a,b.Rb?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function ob(b,a){b.Rb&&b.Sc!==a&&(b.fa.pan.value=a,b.Sc=a)}function U(b,a){b.Ia=a;b.G.gain.cancelScheduledValues(0);b.Pa=-1;b.G.gain.value=b.lc()}function Jb(b,a){a=!!a;b.Qa!==a&&(b.Qa=a,b.Jb())}
function nb(b,a,c,d,e){if(b.nb){var f=b.Ua,g=b.Ta,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Nc?b.u.Hc:performance.now()/1E3}
self.$c=class{constructor(b,a,c){this.u=b;this.O=a;this.ga=c;this.Kb=Mb++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.nb=!1;this.Ua=[0,0,0];this.Ta=[0,0,0];this.ra=[0,0,0];this.fa=null;this.Rb=!1;this.Sc=0;this.I=!0;this.X=this.sa=this.K=!1;this.Ia=1;this.Qa=!1;this.ma=1;b=this.u.Uc;this.Nc=1===b&&!this.za()||2===b;this.Pa=this.pa=-1;this.Md=!1}j(){this.O=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}na(){return Eb(this.u,this.ga)}kc(){return this.O.kc()}eb(){return this.O.eb()}jc(){return this.O.jc()}za(){return this.O.za()}U(){}hc(){}IsPlaying(){return!this.I&&!this.K&&!this.U()}Ja(){}ha(){return this.O.ha()}Play(){}Ba(){}gb(){}Eb(){}La(b){-1!==this.Pa&&b>=this.Pa&&(this.Pa=-1,this.Md&&this.Ba(),Hb(this.u,"fade-ended",this.ga,this.Kb))}lc(){const b=this.Ia;return isFinite(b)?b:0}Cb(){return this.u.Cb()}Jb(){}pc(){}Da(){}oc(){}qc(){}mc(){}cb(){var b=this.Kb,
a=this.ga,c=this.ha(),d=-1===this.Pa?this.Ia:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ua,orient:this.Ta,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ja(),playbackRate:this.ma,uid:this.pa,bufferOriginalUrl:this.kc(),bufferUrl:"",bufferType:this.jc(),isMusic:this.za(),isLooping:this.X,isMuted:this.Qa,resumePosition:this.mc(),pan:f,stereoPan:this.fa?this.Sc:
null}}vc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Da());Jb(this,b.isMuted)}};"use strict";
self.ce=class extends self.$c{constructor(b,a,c){super(b,a,c);this.O.vb.connect(this.G);this.O.onended=()=>this.xc()}j(){this.Ba();this.O.vb.disconnect();super.j()}T(){return this.O.T()}xc(){this.I=!0;this.pa=-1;Hb(this.u,"ended",this.ga,this.Kb)}U(){return this.T().ended}hc(){return this.I?!0:this.U()}Ja(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.eb()}' to position '${c}': `,e)}this.u.Ca(d);this.K=this.I=!1;this.X=b;this.ma=1}Ba(){const b=this.T();b.paused||b.pause();this.u.Ka(b);this.I=!0;this.K=!1;this.pa=-1}gb(){if(!(this.K||this.I||this.U())){var b=this.T();b.paused||b.pause();this.u.Ka(b);this.K=!0}}Eb(){!this.K||this.I||this.U()||(this.u.Ca(this.T()),this.K=!1)}Jb(){this.T().muted=this.Qa||this.Cb()}pc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Da(){let b=this.ma;this.Nc&&(b*=this.u.cc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}oc(b){if(!this.I&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}mc(){return this.Ja()}qc(b){b?this.IsPlaying()?(this.T().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Ca(this.T()),this.sa=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.hb=null}
self.ee=class extends self.$c{constructor(b,a,c){super(b,a,c);this.o=null;this.Wb=d=>this.xc(d);this.Ic=!0;this.hb=null;this.P=this.Xb=this.Zb=0;this.Qc=1}j(){this.Ba();W(this);this.Wb=null;super.j()}xc(b){this.K||this.sa||b.target!==this.hb||(this.I=this.Ic=!0,this.pa=-1,W(this),Hb(this.u,"ended",this.ga,this.Kb))}U(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Ic}hc(){return!this.o||this.I?!0:this.U()}Ja(){let b;b=this.K?this.P:this.Xb+(V(this)-this.Zb)*this.ma;this.X||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Qc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ja;this.o.connect(this.G);this.hb=this.o;this.o.onended=this.Wb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Ic=!1;this.X=b;this.ma=1;this.Zb=V(this);this.Xb=c}Ba(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.pa=-1}gb(){this.K||this.I||this.U()||(this.P=this.Ja(),this.X&&(this.P%=this.ha()),this.K=!0,this.o.stop(0))}Eb(){!this.K||this.I||this.U()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Wb,this.o.loop=this.X,U(this,this.Ia),this.Da(),this.o.start(0,this.P),this.Zb=V(this),this.Xb=this.P,this.K=!1)}lc(){return super.lc()*this.Qc}Jb(){this.Qc=this.Qa||this.Cb()?0:1;U(this,this.Ia)}pc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Da(){let b=this.ma;this.Nc&&(b*=this.u.cc);this.o&&(this.o.playbackRate.value=b)}oc(b){this.I||this.U()||(this.K?this.P=b:(this.gb(),this.P=
b,this.Eb()))}mc(){return this.P}qc(b){b?this.IsPlaying()?(this.sa=!0,this.P=this.Ja(),this.X&&(this.P%=this.ha()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Wb,this.o.loop=this.X,U(this,this.Ia),this.Da(),this.o.start(0,this.P),this.Zb=V(this),this.Xb=this.P,this.sa=!1)}vc(b){super.vc(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Ad=-1;this.R=this.ga="";this.m=null}j(){this.g=null}N(){}S(){}cb(){return{type:this.R,tag:this.ga,params:this.m}}}
self.Vd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.Td=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.sb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.lb=X(this);this.lb.gain.value=c;this.A.connect(this.sb);this.A.connect(this.h);this.sb.connect(this.i);this.sb.connect(this.W);this.W.connect(this.lb);this.lb.connect(this.sb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.sb.disconnect();
this.W.disconnect();this.lb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){const e=self.ab.bd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.lb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.Sd=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.pd=this.od="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.kb=this.g.createConvolver();this.kb.normalize=c;this.kb.buffer=a;this.A.connect(this.kb);this.A.connect(this.h);this.kb.connect(this.i)}j(){this.A.disconnect();this.kb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}cb(){const b=super.cb();b.bufferOriginalUrl=this.od;b.bufferUrl="";b.bufferType=this.pd;return b}};
self.Wd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.mb=X(this);this.mb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.A.connect(this.W);this.A.connect(this.h);this.W.connect(this.i);this.W.connect(this.mb);this.mb.connect(this.W);this.B.connect(this.L);
this.L.connect(this.W.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.W.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.mb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.mb.gain,a/100,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.Xd=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.ab.bd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.$d=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ae=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Zd=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.xb=X(this);this.xb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.xb.gain);this.B.start(0);this.A.connect(this.xb);this.A.connect(this.h);this.xb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.xb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Ud=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.A=X(this);this.ac=X(this);this.$b=X(this);b=d;.01>b&&(b=.01);this.ac.gain.value=b;this.$b.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.dc=this.g.createWaveShaper();this.Ec=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ec[32768+e]=f,this.Ec[32768-
e-1]=-f;this.dc.curve=this.Ec;this.A.connect(this.ac);this.A.connect(this.h);this.ac.connect(this.dc);this.dc.connect(this.$b);this.$b.connect(this.i)}j(){this.A.disconnect();this.ac.disconnect();this.dc.disconnect();this.$b.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Rd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Qd=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.wd=new Float32Array(this.l.frequencyBinCount);this.Ld=new Uint8Array(a);this.Jd=this.Va=0;b=this.u;b.Na.add(this);T(b)}j(){this.u.Na.delete(this);this.l.disconnect();super.j()}La(){this.l.getFloatFrequencyData(this.wd);this.l.getByteTimeDomainData(this.Ld);const b=this.l.fftSize;let a=this.Va=0;for(var c=0;c<b;++c){let d=(this.Ld[c]-
128)/128;0>d&&(d=-d);this.Va<d&&(this.Va=d);a+=d*d}c=self.ab.le;this.Va=c(this.Va);this.Jd=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
